version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - "${TYPEORM_HOST_PORT}:${TYPEORM_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_PORT: ${API_PORT}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_MIGRATIONS: ${TYPEORM_MIGRATIONS}
      TYPEORM_MIGRATIONS_DIR: ${TYPEORM_MIGRATIONS_DIR}
    depends_on:
      - db
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
