export const USER_EXIST = 'USER_EXIST'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const USER_ALREADY_VALIDATED = 'USER_ALREADY_VALIDATED'
export const USER_NOT_ACTIVED = 'USER_NOT_ACTIVED'
export const USER_PASS_EMPTY = 'USER_PASS_EMPTY'
export const USER_INVALID_CODE = 'USER_INVALID_CODE'
export const USER_PASS_ALREADY_DEFINED = 'USER_PASS_ALREADY_DEFINED'
export const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND'
export const USER_IS_BLOCKED = 'USER_IS_BLOCKED'

export const FINAL_USER_CANT_BE_CREATED = 'FINAL_USER_CANT_BE_CREATED'
export const FINAL_USER_NOT_FOUND = 'FINAL_USER_NOT_FOUND'

export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL'
export const DUPLICATE_PHONE = 'DUPLICATE_PHONE'
export const DUPLICATE_CPF = 'DUPLICATE_CPF'

export const ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND'
export const FAILURE_IN_DELETE_ADDRESS = 'FAILURE_IN_DELETE_ADDRESS'
export const FAILURE_IN_DELETE_USER = 'FAILURE_IN_DELETE_USER'

export const FAILURE_IN_GET_USERS = 'FAILURE_IN_GET_USERS'
export const FAILURE_UPDATE_USER = 'FAILURE_UPDATE_USER'
